### ISSUE TITLE
loading nonexist yaml file for rosparam doesn't cause failure

### ISSUE THREAD

**Issue by mikexing2018** [xqms/rosmon#94] opened 2019-08-09 00:14 UTC
if my launch xml file has something like <rosparam command='load' file='abc.yaml'>, rosmon doesn't fail if abc.yaml doesn't exist.  Roslaunch seems to fail and throw an error. Is there a reason for this difference in behavior?

**Comment by xqms** [comment] 2019-08-09 09:31
Hm, in my case I get an error:

```
<launch>
        <rosparam command="load" file="/tmp/not_there.yaml" />
</launch>
```

leads to:

```
$ mon launch test.launch 
Could not load launch file: test.launch:2: Could not open file '/tmp/not_there.yaml'
```

Which version of rosmon are you using? Compiled from source or repository packages?
Could you share a minimum example of a full launch file demonstrating your problem?

**Comment by xqms** [comment] 2019-10-05 12:44
Do you have any further details on this issue? Otherwise I'll close it since I cannot reproduce it.

**Comment by xqms** [comment] 2019-10-07 09:45
I'll close this for now. If you have more details, feel free to reply and I'll reopen the issue.

**Closed by xqms** 2019-10-07 09:45 UTC

**Comment by mikexing2018** [comment] 2019-10-07 19:40
Yes. Closing it is fine. THanks.
