### ISSUE TITLE
logwarn, logerr behavior

### ISSUE THREAD

**Issue by leviathan747** [xqms/rosmon#147] opened 2021-06-28 17:55 UTC
Hi, I'm having a bit of an issue with logging. I'm running a node using Python 3 (need a `python3` only module) and using `asyncio`. I was getting all my "INFO" logs in the monitor, but none of the "WARN" or "ERROR" level logs.

A couple of things I noticed/confirmed during debugging:
- All of the logs were getting published to `/rosout` (confirmed with `rostopic echo`)
- I am still able to get all log types in my Python 2 nodes, however they are all colored with white text (not red or yellow to indicate level; see screenshots to see difference between `roslaunch` and `rosmon`)

![Screenshot from 2021-06-28 13-46-49](https://user-images.githubusercontent.com/2875522/123681919-6168b980-d818-11eb-81bb-eba3cd35817f.png)
![Screenshot from 2021-06-28 13-47-57](https://user-images.githubusercontent.com/2875522/123681932-64fc4080-d818-11eb-8039-3bf55e26252b.png)

I'm sure there's something different about how rosmon captures the logs, but I wasn't able to find documentation anywhere. Can I get some help? I could make all my logs info, but I'd prefer not to...

**Comment by xqms** [comment] 2021-07-02 10:26
Thanks for reporting, that is definitely a bug. I was able to reproduce this on my machine (with Python 3). I'll look deeper into it, I suspect the python nodes are not properly flushing their stderr for some reason, because the messages appear as soon as the node exits.

**Comment by xqms** [comment] 2021-07-06 08:27
Should be fixed now in master. Could you please test if both issues are gone now?

**Comment by leviathan747** [comment] 2021-07-09 20:05
It works (ROS Melodic on Ubuntu 18.04). Will this be in a melodic release soon?

**Comment by xqms** [comment] 2021-08-02 10:37
Thanks for the feedback. I'll create a new release today.

**Closed by xqms** 2021-08-02 10:37 UTC
